version: 2.1
  jobs:
    serialize:
      docker:
        - image: barksim/bark:latest
      steps:
        - checkout
        - run:
            name: Run Serializer
            command: |
              bash ./util/setup_test_venv.sh
              source ./into_test_venv.sh
              bazel --host_jvm_args=-Xmx4g --host_jvm_args=-Xms512m test --jobs=1 //...